// Ported from legacy-src/movies-config.js (generated, then maintained by hand).
import type { CollectionConfig } from "@/lib/collection/types";

export const movies: CollectionConfig = {
  key: "movies",
  brand: "Backlog",
  kicker: "// movies",
  noun: "title",
  nounPlural: "titles",
  theme: {
    bg: "#0c0d12",
    surface: "#12131b",
    card: "#13141c",
    topchip: "#14151d",
    inset: "#0f1016",
    chip: "#202230",
    chip2: "#171826",
    text: "#e7e8ef",
    text2: "#cccedd",
    text3: "#b7b9cc",
    muted2: "#9598b0",
    muted: "#83879c",
    dim: "#565a72",
    dim2: "#383b4c",
    accent2: "#cbceef",
    accent: "#a9aee0",
  },
  fields: { score: "rating", hours: "runtime", price: "price", platform: "watchedOn" },
  addLabel: "+ Add title",
  reviewLabel: "Mi opinión",
  reviewPlaceholder: "Tus pensamientos sobre la película o serie…",
  reviewEmpty: "Sin notas todavía.",
  emptyTitle: "Your watchlist is empty",
  emptySub: "Add your first movie or series to get started.",
  searchFields: ["title", "director", "creator", "studio", "genres", "cast", "watchedOn", "type", "status", "notes"],
  tagField: "genres",
  statusField: "status",
  statuses: [
    {
      value: "watching",
      label: "Watching",
      dot: "var(--accent,#a9aee0)",
      glow: "0 0 8px color-mix(in srgb, var(--accent) 70%, transparent)",
      text: "var(--accent,#a9aee0)",
      reelDot: "var(--accent,#a9aee0)",
      reelGlow: true,
    },
    {
      value: "completed",
      label: "Completed",
      dot: "#7d82c0",
      glow: "none",
      text: "#9598b0",
      reelDot: "#7d82c0",
    },
    {
      value: "backlog",
      label: "Backlog",
      dot: "transparent",
      glow: "inset 0 0 0 1.5px #3d4260",
      text: "#9598b0",
      reelDot: "#9598b0",
    },
    { value: "dropped", label: "Dropped", dot: "#565a72", glow: "none", text: "#565a72", reelDot: "#565a72" },
  ],
  defaultStatus: "backlog",
  statusFilters: [
    { value: "all", label: "All" },
    { value: "watching", label: "Watching" },
    { value: "completed", label: "Completed" },
    { value: "backlog", label: "Backlog" },
    { value: "dropped", label: "Dropped" },
  ],
  table: {
    columns: [
      {
        key: "title",
        label: "Title",
        kind: "text",
        width: "1.8fr",
        mobileWidth: "1fr",
        sortable: true,
        primary: true,
      },
      {
        key: "type",
        label: "Type",
        kind: "text",
        width: "0.95fr",
        hideMobile: true,
        sortable: true,
        color: "var(--text3,#b7b9cc)",
      },
      { key: "genres", label: "Genres", kind: "tags", width: "1.3fr", hideMobile: true },
      { key: "status", label: "Status", kind: "status", width: "110px", mobileWidth: "84px", sortable: true },
      {
        key: "year",
        label: "Year",
        kind: "num",
        width: "58px",
        hideMobile: true,
        right: true,
        mono: true,
        color: "#b7b9cc",
        sortable: true,
      },
      {
        key: "rating",
        label: "Rating",
        kind: "score",
        width: "58px",
        mobileWidth: "50px",
        right: true,
        mono: true,
        sortable: true,
      },
    ],
    chevron: { width: "26px", mobileWidth: "22px" },
  },
  detail: {
    reviewField: "notes",
    fields: [
      {
        key: "director",
        label: "Director",
        kind: "text",
        empty: "—",
        showWhen: { field: "type", notIn: ["Series", "Mini-series", "Anime"] },
        searchLink: {
          url: "https://www.google.com/search?q={title} {year} director",
          title: "Search director",
          pulseWhenEmpty: false,
        },
      },
      {
        key: "creator",
        label: "Creator",
        kind: "text",
        empty: "—",
        showWhen: { field: "type", in: ["Series", "Mini-series", "Anime"] },
      },
      { key: "studio", label: "Studio", kind: "text", empty: "—" },
      {
        key: "runtime",
        label: "Runtime · min",
        kind: "text",
        empty: "—",
        showWhen: { field: "type", notIn: ["Series", "Mini-series", "Anime"] },
      },
      {
        key: "episodes",
        label: "Episodes",
        kind: "text",
        empty: "—",
        showWhen: { field: "type", in: ["Series", "Mini-series", "Anime"] },
      },
      {
        key: "epLength",
        label: "Ep. length · min",
        kind: "text",
        empty: "—",
        showWhen: { field: "type", in: ["Series", "Mini-series", "Anime"] },
      },
      {
        key: "seasons",
        label: "Seasons",
        kind: "text",
        empty: "—",
        showWhen: { field: "type", in: ["Series", "Mini-series", "Anime"] },
      },
      {
        key: "imdb",
        label: "IMDb /10",
        kind: "text",
        empty: "—",
        searchLink: { url: "https://www.imdb.com/find/?q={title}", title: "Look up on IMDb", pulseWhenEmpty: true },
      },
      {
        key: "rt",
        label: "Rotten Tomatoes %",
        kind: "text",
        empty: "—",
        searchLink: {
          url: "https://www.rottentomatoes.com/search?search={title}",
          title: "Look up on Rotten Tomatoes",
          pulseWhenEmpty: true,
        },
      },
      { key: "finished", label: "Finished", kind: "text", empty: "—" },
      { key: "watchedOn", label: "Watched on", kind: "text", empty: "—" },
      { key: "awards", label: "Awards", kind: "text", empty: "None" },
      { key: "cast", label: "Main cast", kind: "tags", empty: "—" },
    ],
    cornerLink: {
      field: "imdb",
      url: "https://www.google.com/search?q={title} imdb",
      label: "Search IMDb ↗",
      pulseWhenEmpty: true,
    },
  },
  modal: {
    titleField: "title",
    autoDateField: "dateAdded",
    groups: [
      {
        cols: 1,
        fields: [
          {
            key: "title",
            label: "Title",
            kind: "text",
            placeholder: "Movie or series title",
            dupCheck: true,
          },
        ],
      },
      {
        cols: 1,
        fields: [
          {
            key: "type",
            label: "Type",
            kind: "enum",
            options: ["Movie", "Series", "Mini-series", "Documentary", "Anime"],
          },
        ],
      },
      {
        cols: 1,
        fields: [
          { key: "status", label: "Status", kind: "status" },
        ],
      },
      {
        cols: 1,
        fields: [
          { key: "genres", label: "Genres", kind: "tags" },
        ],
      },
      {
        cols: 2,
        fields: [
          { key: "year", label: "Release year", kind: "number", min: 1900, max: 2035 },
          { key: "rating", label: "My rating /10", kind: "number", min: 0, max: 10, step: 0.5 },
        ],
      },
      {
        cols: 3,
        fields: [
          { key: "imdb", label: "IMDb /10", kind: "number", min: 0, max: 10, step: 0.1 },
          { key: "rt", label: "Rotten Tom. %", kind: "number", min: 0, max: 100, step: 1 },
          { key: "finished", label: "Date finished", kind: "date" },
        ],
      },
      {
        cols: 2,
        showWhen: { field: "type", notIn: ["Series", "Mini-series", "Anime"] },
        fields: [
          { key: "runtime", label: "Runtime (min)", kind: "number", min: 0, step: 1 },
          { key: "director", label: "Director", kind: "text", placeholder: "Director" },
        ],
      },
      {
        cols: 3,
        showWhen: { field: "type", in: ["Series", "Mini-series", "Anime"] },
        fields: [
          { key: "episodes", label: "Episodes", kind: "number", min: 0, step: 1 },
          { key: "epLength", label: "Avg ep. (min)", kind: "number", min: 0, step: 1 },
          { key: "seasons", label: "Seasons", kind: "number", min: 0, step: 1 },
        ],
      },
      {
        cols: 1,
        showWhen: { field: "type", in: ["Series", "Mini-series", "Anime"] },
        fields: [
          { key: "creator", label: "Creator / showrunner", kind: "text", placeholder: "Creator" },
        ],
      },
      {
        cols: 1,
        fields: [
          {
            key: "studio",
            label: "Studio (optional)",
            kind: "text",
            placeholder: "e.g. A24 · HBO · Studio Ghibli",
          },
        ],
      },
      {
        cols: 1,
        fields: [
          { key: "watchedOn", label: "Watched on", kind: "enum", options: ["Home", "Cinema"] },
        ],
      },
      {
        cols: 1,
        fields: [
          { key: "cast", label: "Main cast", kind: "tags" },
        ],
      },
      {
        cols: 1,
        fields: [
          {
            key: "awards",
            label: "Awards (optional)",
            kind: "longtext",
            placeholder: "Oscars, Emmys, festival wins…",
          },
        ],
      },
      {
        cols: 1,
        fields: [
          { key: "dateAdded", label: "Date added", kind: "date" },
        ],
      },
      {
        cols: 1,
        fields: [
          {
            key: "notes",
            label: "Mi opinión",
            kind: "longtext",
            placeholder: "Tus pensamientos sobre la película o serie…",
          },
        ],
      },
    ],
    numberFields: ["rating", "runtime", "episodes", "epLength", "seasons", "imdb", "rt"],
    yearFields: ["year"],
    textFields: ["type", "director", "creator", "studio", "watchedOn", "finished", "dateAdded", "awards", "notes"],
  },
  roulette: {
    defaultStatus: "backlog",
    statusFilters: [
      { value: "backlog", label: "Backlog" },
      { value: "watching", label: "Watching" },
      { value: "all", label: "All" },
    ],
    band: {
      label: "Length · runtime",
      field: "runtime",
      options: [
        { value: "any", label: "Any" },
        { value: "short", label: "< 90m", max: 90 },
        { value: "medium", label: "90–120m", min: 90, max: 120 },
        { value: "long", label: "120m+", min: 120 },
      ],
    },
    reelSub: [
      { field: "runtime", tpl: "{v}m" },
      { field: "rating", tpl: "★ {v}" },
    ],
    winnerScoreField: "rating",
    winnerSubField: "runtime",
    winnerSubSuffix: "m",
    startAction: { field: "status", value: "watching", label: "Start watching", activeLabel: "Already watching" },
  },
  stats: {
    summary: [
      { kind: "count", label: "Total titles" },
      { kind: "statusCount", status: "completed", label: "Completed", accent: true },
      { kind: "statusCount", status: "watching", label: "Watching", accent: true },
      { kind: "statusCount", status: "backlog", label: "Backlog" },
      { kind: "avg", field: "rating", label: "Avg rating" },
      { kind: "completion", status: "completed", label: "Completion", accent: true },
    ],
    strip: [
      { kind: "count", label: "titles" },
      { kind: "statusCount", status: "watching", label: "watching", accent: true },
      { kind: "statusCount", status: "completed", label: "completed" },
      { kind: "statusCount", status: "backlog", label: "backlog" },
      { kind: "avg", field: "rating", label: "avg rating" },
      { kind: "completion", status: "completed", label: "done" },
    ],
    left: [
      {
        kind: "barList",
        title: "Highest rated",
        field: "rating",
        dir: "desc",
        top: 10,
        podium: true,
        barColor: "var(--accent,#a9aee0)",
        valColor: "var(--accent,#a9aee0)",
        scale: 10,
      },
      {
        kind: "tagRating",
        title: "Favourite genres · by rating",
        tag: "genres",
        field: "rating",
        minCount: 2,
        top: 8,
        barColor: "var(--accent,#a9aee0)",
        valColor: "var(--accent,#a9aee0)",
        scale: 10,
      },
      {
        kind: "barList",
        title: "Longest · runtime",
        field: "runtime",
        dir: "desc",
        top: 8,
        barColor: "#7d82c0",
        valColor: "#cccedd",
        suffix: "m",
      },
      {
        kind: "barList",
        title: "Best on IMDb",
        field: "imdb",
        dir: "desc",
        top: 8,
        barColor: "var(--accent,#a9aee0)",
        valColor: "var(--accent,#a9aee0)",
        scale: 10,
        hideWhenEmpty: true,
      },
      { kind: "histogram", title: "Rating distribution", field: "rating", buckets: 10 },
    ],
    right: [
      {
        kind: "statusDonut",
        title: "Library status",
        center: { status: "completed", label: "done" },
        segments: [
          { status: "completed", color: "#7d82c0", legendColor: "#7d82c0" },
          { status: "watching", color: "{accent}", legendColor: "{accent}" },
          { status: "backlog", color: "var(--we)", legendColor: "var(--wk)" },
          { status: "dropped", color: "#383b4c", legendColor: "#383b4c" },
        ],
      },
      {
        kind: "barList",
        title: "Most-watched cast",
        field: "#cast",
        top: 8,
        barColor: "var(--accent,#a9aee0)",
        barOpacity: ".85",
        valColor: "#83879c",
        compact: true,
      },
      {
        kind: "barList",
        title: "Top genres · by count",
        field: "#genres",
        top: 8,
        barColor: "#7d82c0",
        valColor: "#83879c",
        compact: true,
      },
      {
        kind: "barList",
        title: "By type",
        field: "#type",
        top: 6,
        barColor: "#9598b0",
        valColor: "#83879c",
        compact: true,
      },
      {
        kind: "barList",
        title: "Watched on",
        field: "#watchedOn",
        top: 7,
        barColor: "#9598b0",
        valColor: "#83879c",
        compact: true,
      },
      { kind: "byYear", title: "Released by year", field: "year" },
      { kind: "byYear", title: "Watched by year", field: "finished", fromDate: true },
    ],
    shareModules: [
      { key: "summary", label: "Overview", default: true },
      { key: "topRated", label: "Highest rated", default: true },
      { key: "scoreDist", label: "Rating distribution", default: false },
      { key: "status", label: "Library status", default: true },
      { key: "byYear", label: "Released by year", default: false },
    ],
    shareYearField: "year",
  },
};
