// Starter reading list for the Books collection. Registered into the shared
// COLLECTION_SEEDS registry so GamesCollection.loadStarter() can seed it.
window.COLLECTION_SEEDS = window.COLLECTION_SEEDS || {};
window.COLLECTION_SEEDS.books = [
  {"id":"b1","title":"The Name of the Wind","author":"Patrick Rothfuss","series":"The Kingkiller Chronicle","volume":1,"pages":662,"pubYear":"2007","status":"finished","score":9,"language":"English","started":"2023-01-04","finished":"2023-02-10","isbn":"9780756404741","genres":["Fantasy","Magic","Coming of age"],"review":"Kvothe es un narrador increíble, la prosa es hermosa. Ojalá saliera el tercer libro.","synopsis":"A gifted young man grows up to become the most notorious wizard of his world.","dateAdded":"2023-01-01"},
  {"id":"b2","title":"The Wise Man’s Fear","author":"Patrick Rothfuss","series":"The Kingkiller Chronicle","volume":2,"pages":994,"pubYear":"2011","status":"reading","score":null,"language":"English","started":"2024-05-20","finished":"","isbn":"9780756407919","genres":["Fantasy","Magic","Adventure"],"review":"","synopsis":"Kvothe’s story continues across new lands and dangers.","dateAdded":"2024-05-18"},
  {"id":"b3","title":"Dune","author":"Frank Herbert","series":"Dune","volume":1,"pages":688,"pubYear":"1965","status":"finished","score":10,"language":"English","started":"2022-08-01","finished":"2022-09-15","isbn":"9780441172719","genres":["Science Fiction","Politics","Desert","Prophecy"],"review":"Una obra maestra. La construcción de mundo no tiene igual.","synopsis":"On the desert planet Arrakis, a young heir becomes embroiled in a war over the universe’s most valuable substance.","dateAdded":"2022-07-28"},
  {"id":"b4","title":"Project Hail Mary","author":"Andy Weir","series":"","volume":null,"pages":476,"pubYear":"2021","status":"finished","score":9,"language":"English","started":"2023-06-02","finished":"2023-06-20","isbn":"9780593135204","genres":["Science Fiction","Space","Survival","Friendship"],"review":"Rocky es el mejor personaje. Me reí y lloré.","synopsis":"A lone astronaut must save humanity with only fragments of his memory.","dateAdded":"2023-05-30"},
  {"id":"b5","title":"The Way of Kings","author":"Brandon Sanderson","series":"The Stormlight Archive","volume":1,"pages":1007,"pubYear":"2010","status":"backlog","score":null,"language":"English","started":"","finished":"","isbn":"9780765326355","genres":["Fantasy","Epic","War"],"review":"","synopsis":"Epic fantasy on a storm-wracked world of stone and war.","dateAdded":"2024-02-11"},
  {"id":"b6","title":"Educated","author":"Tara Westover","series":"","volume":null,"pages":334,"pubYear":"2018","status":"finished","score":8,"language":"English","started":"2023-03-05","finished":"2023-03-19","isbn":"9780399590504","genres":["Memoir","Nonfiction","Family","Education"],"review":"Impactante y muy bien escrito.","synopsis":"A woman raised off-grid pursues education against all odds.","dateAdded":"2023-03-01"},
  {"id":"b7","title":"Piranesi","author":"Susanna Clarke","series":"","volume":null,"pages":245,"pubYear":"2020","status":"paused","score":7,"language":"English","started":"2024-01-10","finished":"","isbn":"9781635575637","genres":["Fantasy","Mystery","Surreal","Isolation"],"review":"Atmosférico pero me costó engancharme.","synopsis":"A man lives in an infinite labyrinth of halls and statues.","dateAdded":"2024-01-08"},
  {"id":"b8","title":"The Three-Body Problem","author":"Liu Cixin","series":"Remembrance of Earth’s Past","volume":1,"pages":400,"pubYear":"2008","status":"backlog","score":null,"language":"Spanish","started":"","finished":"","isbn":"9780765382030","genres":["Science Fiction","First contact","Physics"],"review":"","synopsis":"Humanity’s first contact with an alien civilization sets off a cosmic conflict.","dateAdded":"2024-04-02"},
  {"id":"b9","title":"Circe","author":"Madeline Miller","series":"","volume":null,"pages":393,"pubYear":"2018","status":"finished","score":9,"language":"English","started":"2022-11-01","finished":"2022-11-18","isbn":"9780316556347","genres":["Fantasy","Mythology","Greek myth","Feminism"],"review":"Hermoso retelling. La voz de Circe es poderosa.","synopsis":"The witch of Greek myth tells her own story.","dateAdded":"2022-10-28"},
  {"id":"b10","title":"Klara and the Sun","author":"Kazuo Ishiguro","series":"","volume":null,"pages":303,"pubYear":"2021","status":"dropped","score":5,"language":"English","started":"2023-09-01","finished":"","isbn":"9780593318171","genres":["Science Fiction","Literary","AI","Loneliness"],"review":"No terminó de atraparme.","synopsis":"An artificial friend observes the human world with hope.","dateAdded":"2023-08-30"},
];
